import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { classDisplayName, groupClassesByProgram, type SchoolClass } from "@/lib/configApi";
import {
  autoGenerateAllTimetables,
  type AutoGenerateResult,
} from "@/lib/timetableApi";

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  sessionId: string;
  sessionName?: string;
  classes: SchoolClass[];
  /** Currently filtered class on the board (empty = all). Pre-selects dialog scope. */
  selectedClassId?: string;
  onGenerated: (result: AutoGenerateResult) => void;
};

export default function AutoGenerateDialog({
  open,
  onOpenChange,
  sessionId,
  sessionName,
  classes,
  selectedClassId = "",
  onGenerated,
}: Props) {
  const { toast } = useToast();
  const [allClasses, setAllClasses] = useState(true);
  const [pickedClassIds, setPickedClassIds] = useState<string[]>([]);
  const [defaultWeeklyPeriods, setDefaultWeeklyPeriods] = useState(4);
  const [balanceSubjects, setBalanceSubjects] = useState(true);
  const [preventTeacherConflicts, setPreventTeacherConflicts] = useState(true);
  const [preventRoomConflicts, setPreventRoomConflicts] = useState(true);
  const [applyParallel, setApplyParallel] = useState(true);
  const [allowSharedLessons, setAllowSharedLessons] = useState(false);
  const [replaceUnlocked, setReplaceUnlocked] = useState(true);
  const [propagateAssignments, setPropagateAssignments] = useState(true);
  const [result, setResult] = useState<AutoGenerateResult | null>(null);

  const resetForm = () => {
    setResult(null);
    setAllClasses(!selectedClassId);
    setPickedClassIds(selectedClassId ? [selectedClassId] : []);
    setDefaultWeeklyPeriods(4);
    setBalanceSubjects(true);
    setPreventTeacherConflicts(true);
    setPreventRoomConflicts(true);
    setApplyParallel(true);
    setAllowSharedLessons(false);
    setReplaceUnlocked(true);
    setPropagateAssignments(true);
  };

  const handleOpenChange = (next: boolean) => {
    if (next) resetForm();
    onOpenChange(next);
  };

  const generateMut = useMutation({
    mutationFn: () =>
      autoGenerateAllTimetables({
        sessionId,
        ...(allClasses || !pickedClassIds.length ? {} : { classIds: pickedClassIds }),
        defaultWeeklyPeriods,
        balanceSubjects,
        preventTeacherConflicts,
        preventRoomConflicts,
        applyParallel,
        allowSharedLessons,
        replaceUnlocked,
        propagateAssignments,
      }),
    onSuccess: (data) => {
      setResult(data);
      const prop = data.summary.assignmentsPropagated
        ? ` · ${data.summary.assignmentsPropagated} assignments copied to empty sections`
        : "";
      toast({
        title: "Draft timetables generated",
        description: `${data.summary.lessonsPlaced} lessons · ${data.summary.unplaced} unplaced · score ${data.summary.score}%${prop}`,
      });
    },
    onError: (e: Error) =>
      toast({
        title: "Auto generate failed",
        description: e.message,
        variant: "destructive",
      }),
  });

  const classGroups = useMemo(() => groupClassesByProgram(classes), [classes]);

  const scopeLabel = useMemo(() => {
    if (allClasses || !pickedClassIds.length) return "All classes (School + 1st/2nd Year)";
    return classes
      .filter((c) => pickedClassIds.includes(c._id))
      .map((c) => classDisplayName(c))
      .join(", ");
  }, [allClasses, pickedClassIds, classes]);

  const toggleClass = (id: string) => {
    setPickedClassIds((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-amber-500" />
            Auto Generate Timetables
          </DialogTitle>
        </DialogHeader>

        {!result ? (
          <div className="space-y-4 text-sm">
            <p className="text-muted-foreground text-xs leading-relaxed">
              Runs the scheduling engine across sections. Fills <strong>draft</strong>{" "}
              ScheduleSlots from teacher assignments. Class Board only displays the result —
              it does not store a separate timetable.
            </p>

            <div className="rounded-lg border bg-muted/30 px-3 py-2 space-y-1 text-xs">
              <div className="flex justify-between gap-2">
                <span className="text-muted-foreground">Session</span>
                <span className="font-medium">{sessionName || sessionId}</span>
              </div>
              <div className="flex justify-between gap-2">
                <span className="text-muted-foreground">Classes</span>
                <span className="font-medium text-right">{scopeLabel}</span>
              </div>
              <div className="flex justify-between gap-2">
                <span className="text-muted-foreground">Days / Periods</span>
                <span className="font-medium">Working days · lecture periods</span>
              </div>
            </div>

            <div className="space-y-2">
              <Label className="text-xs uppercase tracking-wide text-muted-foreground">
                Scope
              </Label>
              <label className="flex items-center gap-2 cursor-pointer">
                <Checkbox
                  checked={allClasses}
                  onCheckedChange={(v) => {
                    setAllClasses(Boolean(v));
                    if (v) setPickedClassIds([]);
                  }}
                />
                <span>All classes in this session</span>
              </label>
              {!allClasses && (
                <div className="max-h-40 overflow-y-auto rounded-md border p-2 space-y-3">
                  {classGroups.map((g) => (
                    <div key={g.key} className="space-y-1.5">
                      <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                        {g.label}
                      </p>
                      {g.classes.map((c) => (
                        <label key={c._id} className="flex items-center gap-2 cursor-pointer pl-1">
                          <Checkbox
                            checked={pickedClassIds.includes(c._id)}
                            onCheckedChange={() => toggleClass(c._id)}
                          />
                          <span>{classDisplayName(c)}</span>
                        </label>
                      ))}
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="weekly-periods">
                Default weekly periods per subject
                <span className="ml-1 text-muted-foreground font-normal">
                  (used when no SubjectRequirement exists)
                </span>
              </Label>
              <input
                id="weekly-periods"
                type="number"
                min={1}
                max={14}
                className="w-full h-9 rounded-md border bg-background px-3"
                value={defaultWeeklyPeriods}
                onChange={(e) => setDefaultWeeklyPeriods(Number(e.target.value) || 4)}
              />
            </div>

            <div className="space-y-2">
              <Label className="text-xs uppercase tracking-wide text-muted-foreground">
                Rules
              </Label>
              {(
                [
                  [balanceSubjects, setBalanceSubjects, "Balance subjects (max 1 of same subject per day)"],
                  [preventTeacherConflicts, setPreventTeacherConflicts, "Prevent teacher conflicts"],
                  [preventRoomConflicts, setPreventRoomConflicts, "Prevent room conflicts"],
                  [applyParallel, setApplyParallel, "Apply Bio/Computer parallel (choice groups)"],
                  [
                    propagateAssignments,
                    setPropagateAssignments,
                    "Copy teacher assignments to sibling sections (e.g. 9th-A → 9th-B/C)",
                  ],
                  [
                    allowSharedLessons,
                    setAllowSharedLessons,
                    "Shared lessons when same teacher across sections (combinedGroupId)",
                  ],
                  [
                    replaceUnlocked,
                    setReplaceUnlocked,
                    "Replace unlocked draft slots before generating",
                  ],
                ] as const
              ).map(([checked, set, label]) => (
                <label key={label} className="flex items-start gap-2 cursor-pointer">
                  <Checkbox
                    className="mt-0.5"
                    checked={checked}
                    onCheckedChange={(v) => set(Boolean(v))}
                  />
                  <span className="text-sm leading-snug">{label}</span>
                </label>
              ))}
            </div>

            <p className="text-[11px] text-amber-700 dark:text-amber-400/90 leading-relaxed">
              Requires teacher assignments in System Config. Locked slots are never overwritten.
              Review the draft Class Board, then Publish.
            </p>
          </div>
        ) : (
          <div className="space-y-4 text-sm">
            <div className="grid grid-cols-2 gap-2">
              <Stat label="Lessons placed" value={result.summary.lessonsPlaced} />
              <Stat label="Shared lessons" value={result.summary.sharedLessons} />
              <Stat label="Parallel lessons" value={result.summary.parallelLessons} />
              <Stat label="Unplaced" value={result.summary.unplaced} warn={result.summary.unplaced > 0} />
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="outline">Score {result.summary.score}%</Badge>
              <Badge variant="secondary">{result.engine}</Badge>
            </div>

            <div className="space-y-2 max-h-48 overflow-y-auto">
              {result.classes.map((c) => {
                const total = c.placed + c.unplaced;
                const pct = total ? Math.round((c.placed / Math.max(total, 1)) * 100) : 100;
                return (
                  <div key={c.classId} className="space-y-1">
                    <div className="flex justify-between text-xs gap-2">
                      <span className="font-medium truncate">
                        {c.classLabel || c.className}
                        {c.programLabel ? (
                          <span className="ml-1 font-normal text-muted-foreground">
                            · {c.programLabel}
                          </span>
                        ) : null}
                      </span>
                      <span className="text-muted-foreground shrink-0">
                        {c.placed} placed
                        {c.unplaced ? ` · ${c.unplaced} left` : ""}
                      </span>
                    </div>
                    <div className="h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-primary transition-all"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>

            {result.unplaced.length > 0 && (
              <div className="rounded-lg border border-amber-500/40 bg-amber-500/5 p-3 space-y-1 max-h-32 overflow-y-auto">
                <p className="text-xs font-medium text-amber-800 dark:text-amber-300">
                  Could not place ({result.unplaced.length} jobs)
                </p>
                {result.unplaced.slice(0, 12).map((u, i) => (
                  <p key={`${u.label}-${i}`} className="text-[11px] text-muted-foreground">
                    {u.label} — {u.remaining} of {u.weeklyPeriods} left ({u.kind})
                  </p>
                ))}
              </div>
            )}

            {(result.skipped?.length || 0) > 0 && (
              <div className="rounded-lg border border-rose-500/30 bg-rose-500/5 p-3 space-y-1 max-h-36 overflow-y-auto">
                <p className="text-xs font-medium text-rose-800 dark:text-rose-300">
                  Skipped sections / classes ({result.skipped!.length}) — often why 1st/2nd Year
                  missing
                </p>
                {result.skipped!.slice(0, 20).map((s, i) => (
                  <p key={`${s.sectionLabel}-${i}`} className="text-[11px] text-muted-foreground">
                    <span className="font-medium text-foreground">{s.sectionLabel}</span>
                    {s.program ? ` · ${s.program}` : ""} — {s.reasons.join("; ")}
                  </p>
                ))}
              </div>
            )}
          </div>
        )}

        <DialogFooter className="gap-2 sm:gap-0">
          {!result ? (
            <>
              <Button variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button
                disabled={generateMut.isPending || (!allClasses && !pickedClassIds.length)}
                onClick={() => generateMut.mutate()}
              >
                {generateMut.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                    Generating…
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-1.5" />
                    Generate Draft
                  </>
                )}
              </Button>
            </>
          ) : (
            <Button
              onClick={() => {
                onGenerated(result);
                onOpenChange(false);
              }}
            >
              Review Timetable
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function Stat({
  label,
  value,
  warn,
}: {
  label: string;
  value: number;
  warn?: boolean;
}) {
  return (
    <div className="rounded-lg border px-3 py-2">
      <div className="text-[11px] text-muted-foreground">{label}</div>
      <div className={`text-lg font-semibold tabular-nums ${warn ? "text-amber-600" : ""}`}>
        {value}
      </div>
    </div>
  );
}
